version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # Consider using secrets for production
      MYSQL_DATABASE: yao
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  yao-amis-admin:
    image: wwsheng009/yao-amis-admin-amd64:latest
    ports:
      - "5099:5099"
    volumes:
      - ./.env.mysql:/data/.env
      - ./upload:/data/app/data/upload
      - ./logs:/data/app/logs
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5099/health"] # Adjust based on actual endpoint
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mariadb_data:

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.24.0.0/16
        - subnet: fd01::/64