version: '3.8'

services:
  pgvector:
    image: ankane/pgvector
    environment:
    - POSTGRES_PASSWORD=123456
    - POSTGRES_USER=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

  yao-amis-admin:
    image: wwsheng009/yao-amis-admin-amd64:latest
    ports:
      - "5099:5099"
    volumes:
      - ./.env.postgres:/data/.env
      - ./upload:/data/app/data/upload
      - ./logs:/data/app/logs

volumes:
  pgvector_data:

# docker network create --ipv6 --subnet fd00::/8 ip6net

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.24.0.0/16  # IPv4
        - subnet: fd01::/64